# Generated by Django 5.1.1 on 2025-01-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_message_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['id']},
        ),
    ]
