# Generated by Django 5.1.1 on 2024-11-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergency',
            name='lgt',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
