# Generated by Django 5.1.1 on 2024-11-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_emergency_created_at_emergency_lat_emergency_lgt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
