# Generated by Django 5.1.1 on 2025-01-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_alter_emergency_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergency',
            options={'ordering': ['-created_at']},
        ),
    ]
