# Generated by Django 5.1.7 on 2025-03-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_alter_emergency_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='lgt',
        ),
        migrations.AddField(
            model_name='emergency',
            name='location',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
